apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ce0clcmao-dotnet-basic-gitops
  description: This is GitOps manifest for ce0clcmao-dotnet-basic   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ce0clcmao-dotnet-basic
    backstage.io/kubernetes-id: ce0clcmao-dotnet-basic 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: chetna14manku-org/ce0clcmao-dotnet-basic-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ce0clcmao-dotnet-basic
